### ISSUE TITLE
Size calculation seems to be incorrect for both Buffers and strings

### ISSUE THREAD

**Issue by lee-houghton** [sheershoff/node-cache-manager-fs-binary#5]
Hello,

I'll send a more complete example later, but what I've noticed is that the `sizeof` module used to calculate the total size of binary data being stored (in order to reject cache items which are too large) actually doesn't special-case Buffer objects, so it iterates through every byte in the Buffer, converts it to a string, and gets its length. A 17MB Buffer is detected as 400MB!

It also seems to be aimed at being used in `localStorage` or maybe calculating memory usage, where one character in a string takes up 2 bytes -- but that isn't the case here, where we're storing UTF8 files and not calculating RAM/localStorage usage.

**Comment by rolandstarke** [comment]
Hello,

Nice spot, You are right sizeof returns rubish in this case. And not only that it consumes tones of CPU.
I was wondering why the library is so slow. Basically Trying to store a file that is 10MB hangs my PC for 10 seconds

Here the code:
```javascript
var sizeof = require("sizeof");

var startTime = Date.now();
console.log('size:', sizeof.sizeof(Buffer.alloc(1000 * 1000 * 10)));
//size: 217779072

console.log('time needed in seconds:', (Date.now() - startTime) / 1000);
//time needed in seconds: 12.732
```

**Comment by lee-houghton** [comment]
It's not related to this issue but I would offer you another cautionary tale if you are using this library - it does not play nicely if you have more than one instance of it using the same directory (e.g. if you are using the node `cluster` module). The caches will all operate independently and will delete each others' files, write the same file multiple times, and so on.

**Comment by rolandstarke** [comment]
Hey, thanks again.

I have started working on a version that works in cluster mode (by using the md5 of the key as the filename)
https://github.com/rolandstarke/node-cache-manager-fs-hash

I will continue working on it when I need it.

**Comment by lee-houghton** [comment]
That's the best approach, I think. If I hadn't found an alternative solution for my needs, that's what I'd be using.

If you want inspiration, I'd suggest to look at nginx's proxy_cache module if you want inspiration - quite simply, it's brilliant 😃 

For example if you're storing a large number of files you may want to split the files across multiple directories for performance reasons, e.g. using the first 1 or 2 characters of the md5 hash.
